server:
  port: 8081

tomcat:
  ajp:
   protocol: AJP/1.3
   port: 8002

spring:
  profiles:
    active: debug
---
spring:
  profiles: debug
  datasource:
    username: ENC(1mMF+C8fRMVx7FDWsWD1Hg==)
    password: ENC(KjltoRkJh7F1UxbHXMDgGoLpp16+1KpA)
    driver-class-name: oracle.jdbc.OracleDriver
    url: ENC(nXnj6Lx6gI44VuI7pNBnB8P1N6grm5/AOgb8sEZCPCwNN0ubWZNHyjujbmlGVmzxiYZbuL0ixMUlm3JZ5uk4nvFGA0HTVFgwghNJaFN1nMk=)
    
  jpa: 
    show-sql: true
    hibernate:
      ddl-auto: none
    properties: 
      hibernate: 
        dialect: org.hibernate.dialect.OracleDialect
        temp.use_jdbc_metadata_defaults: false

---
spring: 
  profiles: release
  datasource:
    username: ENC(eqp8o3Jy6ho+oqFMcp0MJA==)
    password: ENC(NgfQWYODKdrIykPuyOoCZeVS0VjY/Mut)
    driver-class-name: oracle.jdbc.OracleDriver
    url: ENC(lUBPaY9VxqXAVhaDFlUQIEppaIr7uRFCIJpvLKJA8ZBCGtUEaVp/LJikGnr7K3pbq8Zdvswuzixkl/mjGlZUTA==)

  jpa: 
    show-sql: true
    hibernate:
      ddl-auto: none
    properties: 
      hibernate: 
        dialect: org.hibernate.dialect.OracleDialect
        temp.use_jdbc_metadata_defaults: false
      main:
        allow-bean-definition-overriding: true
    database: default
  thymeleaf:
        prefix : classpath:/templates/
        suffix : .html
        cache : false
        check-template-location: true
        order : 0
---
security: 
  oauth2:
    client:
      auto-approve-scopes: ".*"
    authorization:
      token-key-access: isAuthenticated()
kafka:
   bootstrapAddress: localhost:9092
message:
   topic: mytopic
jasypt:
  encryptor:
    bean: jasyptStringEncryptor     